repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/clairBuoyant/pre-commit
    rev: v0.1.1
    hooks:
      - id: branch-validate
# TODO:
# add formatter for bash: https://github.com/lovesegfault/beautysh (and for server)
# add eslint: https://github.com/pre-commit/mirrors-eslint
# add prettier: https://github.com/pre-commit/mirrors-prettier
# add commitizen: https://github.com/commitizen-tools/commitizen
# research whether https://github.com/MarcoGorelli/absolufy-imports is viable
