#!/bin/bash -e
#
# Load scripts to current shell environment for execution without package manager.

PROJECT_ROOT=$(realpath $(dirname "$BASH_SOURCE"))

function bootstrap() {
    ${PROJECT_ROOT}/scripts/bootstrap
}
function clean() {
    ${PROJECT_ROOT}/scripts/clean
}
function init() {
    ${PROJECT_ROOT}/scripts/init
}
function setup() {
    ${PROJECT_ROOT}/scripts/setup
}
function start() {
    ${PROJECT_ROOT}/scripts/start
}
function uninstall() {
    ${PROJECT_ROOT}/scripts/uninstall
}

echo 'Script commands are ready to use in current shell environment.'
