#!/bin/bash -e
#
# Resolve all system dependencies the application needs to run.

PYV=`python3 -c 'import sys; sys.stdout.write("true") if sys.version_info.major >= 3 and sys.version_info.minor >= 10 else sys.stdout.write("false");'`
if ! $PYV
then
    echo 'Python version 3.10 or greater is required.'
    exit 1
fi

JSV=`node -e 'const [major, minor] = process.version.slice(1).split(".").map(n => Number(n)); major >= 18 && minor >= 7 ? console.log("true") : console.log("false");'`
if ! $JSV
then
    echo 'Node version 18.7 or greater is required.'
    exit 1
fi

echo 'Checking for pre-commit...'
if ! command -v pre-commit &> /dev/null
then
    echo 'pre-commit not found. Installing with pipx...'
    if ! command -v pipx &> /dev/null
    then
        echo 'pipx was not found. Installing pipx first...'
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
    fi
    pipx install pre-commit
fi

echo 'System dependencies installed.'
