#!/bin/bash -e
#
# Docker entrypoint.

case $1 in
    build)
        npm build
        ;;
    dev)
        npm run dev
        ;;
    preview)
        npm run preview
        ;;
    start)
        npm start
        ;;
    test)
        npm test $@
        ;;
    *)
        npm run "$@"
        ;;
esac
