#!/bin/bash -ex
#
# Remove node dependencies and build artifacts.

CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BASE_DIR="$(dirname "$CURRENT_DIR")"

${BASE_DIR}/scripts/clean

if [ -d 'node_modules' ] ; then
    rm -r node_modules
fi
